### ISSUE TITLE
feat: improve nft by creating an nft picture

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeAcademy/ERC721#14]
coming soon nft picture
switch the uri for the reveal

image coming soon
every nft has a metadata standard JSON file
attribute is the image uri

UPLoad image: IPFS
Make metadata file with IPFS URI
name and descipt

opensea: has more stuff

content upload to IPFS send content ID

10,000 meta to refernce metafile

make IPFS folder routes to hash
and that the baseURI
1.json CID,--10K

upload that to image metadata file, you the hash file folder to reference, uplaod that file to get base uri

folder file base uri/1.json
folder file base uri/2.json
folder file base uri/3.json

funcation to token to string, vyper 0.3.4 built in stringify and remove it

folder CID/ 1.json == metadata file its on an IP 
pinata- host ipfs service like infura

opensea test kovan
render properly

show them how to change metadata

**Comment by agBabbbyCakes** [comment]
please follow thru - @Ninjagod1251 @NotPeopling2day

**Comment by sabotagebeats** [comment]
@agBabbbyCakes 👋

**Comment by NotPeopling2day** [comment]
Closing https://linear.app/apeworx/issue/ACA-4/feat-improve-nft-by-creating-an-nft-picture
