### ISSUE TITLE
Permitable is included as an option in the cookiecutter prompt

### ISSUE THREAD

**Issue by unparalleled-js** [ApeAcademy/ERC721#39]
I noticed the last option in the prompt is for `permitable`. Are NFTs meant to have permitable? I noticed it was part of the cookie cutter prompt, but I don't see it in the ERC-721 spec or in the OpenZeppelin Wizard tool.

**Comment by fubuloubu** [comment]
It's a new spec, still in Draft but it's here: https://eips.ethereum.org/EIPS/eip-4494
